# Generated by Django 5.2.17 on 2026-09-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100, unique=True)),
                ('org_id', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=100, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=100)),
                ('event_date', models.CharField(blank=True, max_length=100)),
                ('category_code', models.CharField(blank=True, max_length=100)),
                ('actor_id', models.CharField(blank=True, max_length=100)),
                ('base_value', models.TextField(blank=True)),
                ('adjustment', models.TextField(blank=True)),
                ('total_value', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100, unique=True)),
                ('record_ref', models.CharField(blank=True, max_length=100)),
                ('normalized_record_ref', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location_id', models.CharField(blank=True, max_length=100)),
                ('recorded_on', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField(blank=True)),
                ('label', models.TextField(blank=True)),
            ],
        ),
    ]
